#!/bin/bash

DISQUE_DIR="${DISQUE_DIR:-$(pwd -P)/disque}"
DISQUE_CMD="${DISQUE_DIR}/src/disque"

disque_kill () {
    #for i in $@; do
    for i in 7711 7712 7713 7714; do
        #${DISQUE_CMD} -p $i shutdown >/dev/null 2>&1
        disque -p $i shutdown >/dev/null 2>&1
    done
    echo 'Cluster destroyed'
}

disque_kill $@
